on:
    workflow_dispatch:
      inputs:
        #Change this value
        solution_name:
          description: 'name of the solution to worked on from Power Platform'
          required: true
          default: LicenciApp
         #Do Not change these values
        solution_exported_folder:
          description: 'folder name for staging the exported solution *do not change*'
          required: true
          default: out/exported/
        solution_folder:
          description: 'staging the unpacked solution folder before check-in *do not change*'
          required: true
          default: out/solutions/
        solution_target_folder: 
         description: 'folder name to be created and checked in *do not change*'
         required: true
         default: solutions/
env:
 PROD_ENVIRONMENT_URL    : 'https://t2-powepro01.crm.dynamics.com/'
jobs:
  Export-from-Dev:
      runs-on: windows-latest
      environment:  Development
      steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: export-unmanaged-solution action (No Administrada)
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          environment-url     : ${{env.PROD_ENVIRONMENT_URL}}
          app-id              : ${{secrets.CLIENT_ID}}
          client-secret       : ${{secrets.CLIENT_SECRET}}
          tenant-id           : ${{secrets.TENANT_ID}}
          solution-name       : ${{github.event.inputs.solution_name}}
          solution-output-file: ${{github.event.inputs.solution_exported_folder}}/${{github.event.inputs.solution_name}}.zip
      - name: export-managed-solution action (Administrada)
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          environment-url     : ${{env.PROD_ENVIRONMENT_URL}}
          app-id              : ${{secrets.CLIENT_ID}}
          client-secret       : ${{secrets.CLIENT_SECRET}}
          tenant-id           : ${{secrets.TENANT_ID}}
          solution-name       : ${{github.event.inputs.solution_name}}
          solution-output-file: ${{github.event.inputs.solution_exported_folder}}/${{github.event.inputs.solution_name}}_managed.zip
          managed             : true
      - name: unpack-solution action
        uses: microsoft/powerplatform-actions/unpack-solution@v0
        with:
          solution-file       : ${{github.event.inputs.solution_exported_folder}}/${{github.event.inputs.solution_name}}.zip
          solution-folder     : ${{github.event.inputs.solution_folder}}/${{github.event.inputs.solution_name}}
          solution-type       : 'Both'
      - name: branch-solution, prepare it for a PullRequest
        uses: microsoft/powerplatform-actions/branch-solution@v0
        with:
          solution-folder       : ${{github.event.inputs.solution_folder}}/${{github.event.inputs.solution_name}}
          solution-target-folder: ${{github.event.inputs.solution_target_folder}}/${{github.event.inputs.solution_name}}
          repo-token            : ${{secrets.GITHUB_TOKEN}}
          allow-empty-commit    : true
