name: Hello

on:
    push:
        branches:
            - master
jobs:
    hello_word:
        runs-on: windows-latest
        steps:
         - name: Check out repository code
           uses: actions/checkout@v4
         - name: Install Power Platform CLI
           run: |
                Invoke-WebRequest -Uri https://aka.ms/powerplatform-cli/download -OutFile ppcli.msi
                Start-Process msiexec -Wait -ArgumentList '/i ppcli.msi /quiet /norestart'
           shell: pwsh
         - name: Connect to Power Apps
           run: |
                pac auth login --environment "d5902e03-c12a-490f-89ca-ef381d7eb834" --username "christianVegaCervantes@UFRP294.onmicrosoft.com" --password "4l0ns0CV"
           shell: pwsh
         - name: List Power Apps Solutions
           run: |
                pac solution list
           shell: pwsh
