name: Hello

on:
    push:
        branches:
            - master
jobs:
    hello_word:
        runs-on: windows-latest
        steps:
         - name: Check out repository code
           uses: actions/checkout@v4
         - name: Install Power Platform CLI
           run: |
                Invoke-WebRequest -Uri https://aka.ms/powerplatform-cli/download -OutFile ppcli.msi
                Start-Process msiexec -Wait -ArgumentList '/i ppcli.msi /quiet /norestart'
           shell: pwsh
         - name: Debug Output
           run: |
                echo "Debug information..."
                # Agrega más comandos de depuración según sea necesario
           shell: pwsh
