name: Say Hello

on:
    push:
        branches:
            - main
jobs:
    hello_word:
        runs-on: ubuntu-18.04
        steps:
            - name: Echo the message
              run: echo "Hola christian!"
              