name: pipeline
on:
    push:
        branches:
            - master
jobs:
    build:
  
      runs-on: windows-latest   # alternate runner OS is: ubuntu-latest
  
      steps:
      - name: powerplatform-actions
        uses: microsoft/powerplatform-actions@v0.10.10