name: Deployment Pipeline
on:
    push:
        branches:
          - master
jobs:
    deploy:
        runs-on: ubuntu-lates
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0