name: pipeline
on:
    push:
        branches:
            - master
jobs:
    build:
  
      runs-on: windows-latest   # alternate runner OS is: ubuntu-latest
  
      steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
             lfs: true

      - name: powerplatform-actions
        uses: microsoft/powerplatform-actions@v0.10.10
        with:
          environment-url: 'https://user9-dev.crm.dynamics.com/'
          user-name: 'user9@wrkdevops.onmicrosoft.com'
          password-secret: ${{ secrets.password }}