on:
    release:
        types: [created] 
env:
    solution_name           : LicenciApp
    solution_source_folder  : solutions
    solution_outbound_folder: out/solutions
    solution_release_folder : out/release
    CERT_ENVIRONMENT_URL    : 'https://org8b325d37.crm.dynamics.com/'
jobs:
    convert-to-managed:
     runs-on: windows-latest
     
     steps:
     - uses: actions/checkout@v3
       with:
         lfs: true
     - name: Install NuGet
       run: |
           choco install nuget.commandline -y
       shell: powershell
     - name: Install PAC
       uses: microsoft/powerplatform-actions/actions-install@v1
       with:
         pac-version-override: 1.28.3
     - name: Pack managed solution
       uses: microsoft/powerplatform-actions/pack-solution@v1
       with:
         solution-folder: ${{env.solution_source_folder}}/${{env.solution_name}}
         solution-file  : ${{env.solution_outbound_folder}}/${{env.solution_name}}_managed.zip
         solution-type  : Managed

     - name: Pack unmanaged solution
       uses: microsoft/powerplatform-actions/pack-solution@v1
       with:
         solution-folder: ${{env.solution_source_folder}}/${{env.solution_name}}
         solution-file  : ${{env.solution_outbound_folder}}/${{env.solution_name}}_unmanaged.zip
         solution-type  : Unmanaged

     - name: Upload the unmanaged solution to GH artifact store
       uses: actions/upload-artifact@v3
       with:
         name: unmanagedSolutions
         path: ${{env.solution_outbound_folder}}/${{env.solution_name}}_unmanaged.zip       
        
     - name: Upload the managed solution to GH artifact store
       uses: actions/upload-artifact@v3 
       with:
         name: managedSolutions
         path: ${{env.solution_outbound_folder}}/${{env.solution_name}}_managed.zip
         
    release-to-staging:
      needs: [ convert-to-managed ]
      runs-on: windows-latest
      environment: Production 
      steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Fetch the ready to ship solution from GH artifact store
        uses: actions/download-artifact@v1
        with:
          name: managedSolutions
          path: ${{env.solution_release_folder}}
      - name: Import solution to prod env
        uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url   : ${{env.CERT_ENVIRONMENT_URL}}
          app-id            : ${{secrets.CLIENT_ID}}
          client-secret     : ${{secrets.CLIENT_SECRET}}
          tenant-id         : ${{secrets.TENANT_ID}}
          solution-file     : ${{env.solution_release_folder}}/${{env.solution_name}}_managed.zip
          run-asynchronously: true
          force-overwrite   : true
          publish-changes   : true
